Traceback (most recent call last):
  File "main.py", line 70, in <module>
    model = model.to(device)
NameError: name 'device' is not defined
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    model = model.to(device)
NameError: name 'device' is not defined