
Epoch: 1
torch.Size([98, 100, 100, 3])
torch.Size([98, 100, 100, 3])
torch.Size([98, 100, 100, 3])
torch.Size([98, 100, 100, 3])
torch.Size([98, 100, 100, 3])
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    train_loss = train_func(model, loader_train, optimizer, scaler)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/train.py", line 23, in train_func
    for images, targets in loader_train:
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/Dataloader.py", line 47, in __getitem__
    image = transforms_train(image=image)['image']
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/core/composition.py", line 205, in __call__
    data = t(**data)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 118, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 131, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/augmentations/transforms.py", line 1120, in apply
    return F.brightness_contrast_adjust(img, alpha, beta, self.brightness_by_max)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 836, in brightness_contrast_adjust
    return _brightness_contrast_adjust_non_uint(img, alpha, beta, beta_by_max)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/augmentations/utils.py", line 68, in wrapped_function
    return clip(func(img, *args, **kwargs), dtype, maxval)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 804, in _brightness_contrast_adjust_non_uint
    max_value = MAX_VALUES_BY_DTYPE[dtype]
KeyError: dtype('int16')
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    train_loss = train_func(model, loader_train, optimizer, scaler)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/train.py", line 23, in train_func
    for images, targets in loader_train:
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/Dataloader.py", line 47, in __getitem__
    image = transforms_train(image=image)['image']
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/core/composition.py", line 205, in __call__
    data = t(**data)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 118, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 131, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/augmentations/transforms.py", line 1120, in apply
    return F.brightness_contrast_adjust(img, alpha, beta, self.brightness_by_max)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 836, in brightness_contrast_adjust
    return _brightness_contrast_adjust_non_uint(img, alpha, beta, beta_by_max)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/augmentations/utils.py", line 68, in wrapped_function
    return clip(func(img, *args, **kwargs), dtype, maxval)
  File "/homes/n20darja/.local/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 804, in _brightness_contrast_adjust_non_uint
    max_value = MAX_VALUES_BY_DTYPE[dtype]
KeyError: dtype('int16')