
Epoch: 1
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    print('Loss', loss, '\n')
NameError: name 'loss' is not defined
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    print('Loss', loss, '\n')
NameError: name 'loss' is not defined